global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: ${TELEGRAM_BOT_TOKEN}
        chat_id: 391137404
        parse_mode: "HTML"
        send_resolved: true
