services:

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    environment:
      DATA_SOURCE_NAME: "${MYSQL_CONNECTION}"
    networks:
      - monitor-net

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: ${POSTGRES_CONNECTION}
    networks:
      - monitor-net

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: [ "-nginx.scrape-uri=http://${NGINX_HOST:-nginx}:${NGINX_PORT:-80}/stub_status" ]
    networks:
      - monitor-net
    restart: unless-stopped

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    command:
      - "--kafka.server=${KAFKA_HOST}:${KAFKA_PORT:-9092}"
      - "--kafka.version=2.7.0"
    networks:
      - monitor-net
