receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # Принимает подключения gRPC со всех интерфейсов
      http:
        endpoint: "0.0.0.0:4318"  # Принимает подключения HTTP со всех интерфейсов


exporters:
  otlphttp:
    endpoint: "http://jaeger:4318"  # Убедитесь, что порт корректный

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
