apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true  # Prometheus является источником данных по умолчанию
    editable: true

  - name: MySQL
    type: mysql
    url: ${MYSQL_HOST}:3306
    access: proxy
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    secureJsonData:
      password: ${MYSQL_PASSWORD}
